# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lorenzo/PI/RedPitaya-FPGA/prj/v0.94/project/redpitaya.srcs/sources_1/ip/asg_dat_fifo/asg_dat_fifo.xci
# IP: The module: 'asg_dat_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lorenzo/PI/RedPitaya-FPGA/prj/v0.94/project/redpitaya.gen/sources_1/ip/asg_dat_fifo/asg_dat_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'asg_dat_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lorenzo/PI/RedPitaya-FPGA/prj/v0.94/project/redpitaya.gen/sources_1/ip/asg_dat_fifo/asg_dat_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'asg_dat_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lorenzo/PI/RedPitaya-FPGA/prj/v0.94/project/redpitaya.gen/sources_1/ip/asg_dat_fifo/asg_dat_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'asg_dat_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/lorenzo/PI/RedPitaya-FPGA/prj/v0.94/project/redpitaya.srcs/sources_1/ip/asg_dat_fifo/asg_dat_fifo.xci
# IP: The module: 'asg_dat_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lorenzo/PI/RedPitaya-FPGA/prj/v0.94/project/redpitaya.gen/sources_1/ip/asg_dat_fifo/asg_dat_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'asg_dat_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lorenzo/PI/RedPitaya-FPGA/prj/v0.94/project/redpitaya.gen/sources_1/ip/asg_dat_fifo/asg_dat_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'asg_dat_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lorenzo/PI/RedPitaya-FPGA/prj/v0.94/project/redpitaya.gen/sources_1/ip/asg_dat_fifo/asg_dat_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'asg_dat_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
