# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lorenzo/PI/RedPitaya-FPGA/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_axi_protocol_converter_0_0/system_axi_protocol_converter_0_0.xci
# IP: The module: 'system_axi_protocol_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lorenzo/PI/RedPitaya-FPGA/prj/v0.94/project/redpitaya.gen/sources_1/bd/system/ip/system_axi_protocol_converter_0_0/system_axi_protocol_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_protocol_converter_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lorenzo/PI/RedPitaya-FPGA/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_axi_protocol_converter_0_0/system_axi_protocol_converter_0_0.xci
# IP: The module: 'system_axi_protocol_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lorenzo/PI/RedPitaya-FPGA/prj/v0.94/project/redpitaya.gen/sources_1/bd/system/ip/system_axi_protocol_converter_0_0/system_axi_protocol_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_protocol_converter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
