MODULE := mca
TOP    := mca_top
DEPS   :=
TBS    := tb_mca_div_restore \
          tb_mca_hist \
          tb_mca_zoom \
          tb_mca_discriminator \
          tb_mca_pulse_feature \
          tb_mca_top

include ../../mk/module.mk
